version: '3'
services: 
    sampleapp: #container 1
        container_name: docker_app_container
        restart: always
        build: . #build from local dockerfile
        ports:
            - "8045:8045"
        links: 
            - mongodb
    mongodb: #container 2
        container_name: mongodb_container
        image: mongo:latest
        ports:
            - "27016:27017"
